# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\Vincent\Desktop\C++ Games\VimJam4"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\Vincent\Desktop\C++ Games\VimJam4"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Vincent\Desktop\C++ Games\VimJam4\CMakeFiles" "C:\Users\Vincent\Desktop\C++ Games\VimJam4\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Vincent\Desktop\C++ Games\VimJam4\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Paths

# Build rule for target.
Paths: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Paths
.PHONY : Paths

# fast build rule for target.
Paths/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/build
.PHONY : Paths/fast

src/button.o: src/button.cpp.o
.PHONY : src/button.o

# target to build an object file
src/button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/button.cpp.o
.PHONY : src/button.cpp.o

src/button.i: src/button.cpp.i
.PHONY : src/button.i

# target to preprocess a source file
src/button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/button.cpp.i
.PHONY : src/button.cpp.i

src/button.s: src/button.cpp.s
.PHONY : src/button.s

# target to generate assembly for a file
src/button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/button.cpp.s
.PHONY : src/button.cpp.s

src/enemy.o: src/enemy.cpp.o
.PHONY : src/enemy.o

# target to build an object file
src/enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/enemy.cpp.o
.PHONY : src/enemy.cpp.o

src/enemy.i: src/enemy.cpp.i
.PHONY : src/enemy.i

# target to preprocess a source file
src/enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/enemy.cpp.i
.PHONY : src/enemy.cpp.i

src/enemy.s: src/enemy.cpp.s
.PHONY : src/enemy.s

# target to generate assembly for a file
src/enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/enemy.cpp.s
.PHONY : src/enemy.cpp.s

src/font.o: src/font.cpp.o
.PHONY : src/font.o

# target to build an object file
src/font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/font.cpp.o
.PHONY : src/font.cpp.o

src/font.i: src/font.cpp.i
.PHONY : src/font.i

# target to preprocess a source file
src/font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/font.cpp.i
.PHONY : src/font.cpp.i

src/font.s: src/font.cpp.s
.PHONY : src/font.s

# target to generate assembly for a file
src/font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/font.cpp.s
.PHONY : src/font.cpp.s

src/gameStateManager.o: src/gameStateManager.cpp.o
.PHONY : src/gameStateManager.o

# target to build an object file
src/gameStateManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/gameStateManager.cpp.o
.PHONY : src/gameStateManager.cpp.o

src/gameStateManager.i: src/gameStateManager.cpp.i
.PHONY : src/gameStateManager.i

# target to preprocess a source file
src/gameStateManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/gameStateManager.cpp.i
.PHONY : src/gameStateManager.cpp.i

src/gameStateManager.s: src/gameStateManager.cpp.s
.PHONY : src/gameStateManager.s

# target to generate assembly for a file
src/gameStateManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/gameStateManager.cpp.s
.PHONY : src/gameStateManager.cpp.s

src/level.o: src/level.cpp.o
.PHONY : src/level.o

# target to build an object file
src/level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/level.cpp.o
.PHONY : src/level.cpp.o

src/level.i: src/level.cpp.i
.PHONY : src/level.i

# target to preprocess a source file
src/level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/level.cpp.i
.PHONY : src/level.cpp.i

src/level.s: src/level.cpp.s
.PHONY : src/level.s

# target to generate assembly for a file
src/level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/level.cpp.s
.PHONY : src/level.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/menuState.o: src/menuState.cpp.o
.PHONY : src/menuState.o

# target to build an object file
src/menuState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/menuState.cpp.o
.PHONY : src/menuState.cpp.o

src/menuState.i: src/menuState.cpp.i
.PHONY : src/menuState.i

# target to preprocess a source file
src/menuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/menuState.cpp.i
.PHONY : src/menuState.cpp.i

src/menuState.s: src/menuState.cpp.s
.PHONY : src/menuState.s

# target to generate assembly for a file
src/menuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/menuState.cpp.s
.PHONY : src/menuState.cpp.s

src/playState.o: src/playState.cpp.o
.PHONY : src/playState.o

# target to build an object file
src/playState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/playState.cpp.o
.PHONY : src/playState.cpp.o

src/playState.i: src/playState.cpp.i
.PHONY : src/playState.i

# target to preprocess a source file
src/playState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/playState.cpp.i
.PHONY : src/playState.cpp.i

src/playState.s: src/playState.cpp.s
.PHONY : src/playState.s

# target to generate assembly for a file
src/playState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/playState.cpp.s
.PHONY : src/playState.cpp.s

src/selectState.o: src/selectState.cpp.o
.PHONY : src/selectState.o

# target to build an object file
src/selectState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/selectState.cpp.o
.PHONY : src/selectState.cpp.o

src/selectState.i: src/selectState.cpp.i
.PHONY : src/selectState.i

# target to preprocess a source file
src/selectState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/selectState.cpp.i
.PHONY : src/selectState.cpp.i

src/selectState.s: src/selectState.cpp.s
.PHONY : src/selectState.s

# target to generate assembly for a file
src/selectState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Paths.dir\build.make CMakeFiles/Paths.dir/src/selectState.cpp.s
.PHONY : src/selectState.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Paths
	@echo ... src/button.o
	@echo ... src/button.i
	@echo ... src/button.s
	@echo ... src/enemy.o
	@echo ... src/enemy.i
	@echo ... src/enemy.s
	@echo ... src/font.o
	@echo ... src/font.i
	@echo ... src/font.s
	@echo ... src/gameStateManager.o
	@echo ... src/gameStateManager.i
	@echo ... src/gameStateManager.s
	@echo ... src/level.o
	@echo ... src/level.i
	@echo ... src/level.s
	@echo ... src/main.o
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/menuState.o
	@echo ... src/menuState.i
	@echo ... src/menuState.s
	@echo ... src/playState.o
	@echo ... src/playState.i
	@echo ... src/playState.s
	@echo ... src/selectState.o
	@echo ... src/selectState.i
	@echo ... src/selectState.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

